baseURL: http://localhost:3000 # Your app url
projectName: exjobb-spa
samples: 3
containers:
  - "exjobb-spa"
scenarios: 
  - path: ./scenario_home.js
    name: S1 - load home page
  - path: ./scenario_form.js
    name: S2 - fill in form
  - path: ./scenario_feed.js
    name: S3 - scroll trough feed
  - path: ./scenario_navigate.js
    name: S4 - navigate between subpages 